"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from "react";
import { buttonVariants, cx } from "@/lib/classes";
import type { HeroSlide } from "@/lib/content";
import { banners } from "@/lib/meta";

/**
 * Slide copy comes from the editable homepage content (lib/content.ts, admin "Edit homepage")
 * and is rendered as real HTML over the banner art (generated by scripts/gen-banners.mjs), so
 * headlines stay readable by screen readers, selectable, and responsive.
 */
const INTERVAL = 6500;

const motionQuery = "(prefers-reduced-motion: reduce)";
const subscribeMotion = (cb: () => void) => {
  const mq = window.matchMedia(motionQuery);
  mq.addEventListener("change", cb);
  return () => mq.removeEventListener("change", cb);
};

export default function HeroSlider({ slides }: { slides: HeroSlide[] }) {
  const frames = slides
    .filter((s) => s.visible)
    .flatMap((copy) => banners.filter((b) => b.id === copy.id).map((b) => ({ ...b, copy })));
  const [index, setIndex] = useState(0);
  const [keyboardFocus, setKeyboardFocus] = useState(false);
  const [playing, setPlaying] = useState(true);
  const reducedMotion = useSyncExternalStore(
    subscribeMotion,
    () => window.matchMedia(motionQuery).matches,
    () => false
  );

  // Always autoplays unless the visitor presses pause. (It does not pause on hover: the hero is
  // large and sits at the top of the page, so the pointer usually rests on it and the slideshow
  // looked frozen.) Under reduced motion it still advances, but slides switch instantly - the
  // global stylesheet removes the crossfade - so there is no animation, just a content change.
  // Keyboard focus inside the slider pauses it while a keyboard user is working with it.
  const paused = !playing || keyboardFocus;

  // Time left on the current slide survives a pause, so pausing freezes the countdown and
  // resuming continues from where it stopped (the progress bar does the same via animation-play-state).
  const remaining = useRef(INTERVAL);
  const timerSlide = useRef(index);

  const goTo = useCallback((i: number) => setIndex((i + frames.length) % frames.length), [frames.length]);

  useEffect(() => {
    if (timerSlide.current !== index) {
      timerSlide.current = index;
      remaining.current = INTERVAL;
    }
    if (paused || frames.length < 2) return;
    const startedAt = performance.now();
    const t = setTimeout(() => setIndex((i) => (i + 1) % frames.length), remaining.current);
    return () => {
      clearTimeout(t);
      remaining.current = Math.max(0, remaining.current - (performance.now() - startedAt));
    };
  }, [index, paused, frames.length]);

  return (
    <section
      aria-roledescription="carousel"
      aria-label="Featured"
      className="relative overflow-hidden rounded-3xl border border-line bg-void"
      // Only keyboard focus pauses. A mouse click on an arrow also focuses the button, and
      // pausing on that would stop the slideshow for good after any click.
      onFocusCapture={(e) => {
        if ((e.target as HTMLElement).matches(":focus-visible")) setKeyboardFocus(true);
      }}
      onBlurCapture={(e) => {
        if (!e.currentTarget.contains(e.relatedTarget as Node | null)) setKeyboardFocus(false);
      }}
      onKeyDown={(e) => {
        if (e.key === "ArrowRight") goTo(index + 1);
        if (e.key === "ArrowLeft") goTo(index - 1);
      }}
      data-testid="hero-slider"
    >
      <div className="relative aspect-4/5 sm:aspect-video lg:aspect-21/9">
        {frames.map((frame, i) => {
          const { copy } = frame;
          const current = i === index;
          return (
            <div
              key={frame.id}
              role="group"
              aria-roledescription="slide"
              aria-label={`${i + 1} of ${frames.length}: ${copy.title}`}
              aria-hidden={!current}
              inert={!current}
              className={cx("absolute inset-0 transition-opacity duration-700", current ? "opacity-100" : "opacity-0")}
            >
              <Image
                src={`/banners/${frame.full}`}
                alt=""
                fill
                priority={i === 0}
                // the slider is the 80rem page column, and rem grows past 1920px (app/globals.css)
                sizes="(min-width: 1920px) calc(33.4vw + 640px), (min-width: 1280px) 1280px, 100vw"
                className="object-cover object-[78%_50%]"
              />
              {/* readability scrim, heavier on small screens where copy overlaps the art */}
              <div className="absolute inset-0 bg-linear-to-t from-void via-void/70 to-transparent sm:bg-linear-to-r sm:from-void/95 sm:via-void/55 sm:to-transparent" />

              <div className="absolute inset-0 flex items-end p-6 pb-20 sm:items-center sm:p-10 lg:p-14">
                <div className={cx("max-w-md space-y-4", current && "animate-rise")}>
                  <p className="font-mono text-[0.7rem] tracking-[0.26em] text-cyan uppercase">{copy.eyebrow}</p>
                  <h2 className="text-3xl leading-[1.05] font-semibold tracking-tight text-balance sm:text-4xl lg:text-5xl">
                    {copy.title}
                  </h2>
                  <p className="text-sm text-dim sm:text-base">{copy.body}</p>
                  <Link href={copy.href} className={cx(buttonVariants.primary, "mt-2")}>
                    {copy.cta} →
                  </Link>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* controls */}
      <div className="absolute right-4 bottom-4 flex items-center gap-2 sm:right-6 sm:bottom-6">
        <button
          type="button"
          onClick={() => setPlaying((p) => !p)}
          className="grid size-9 place-items-center rounded-full border border-line-bright bg-void/60 text-dim backdrop-blur transition hover:border-cyan hover:text-cyan"
          aria-label={playing ? "Pause slideshow" : "Play slideshow"}
          aria-pressed={!playing}
          data-testid="hero-playpause"
        >
          {playing ? (
            <svg viewBox="0 0 24 24" className="size-3.5" fill="currentColor" aria-hidden>
              <rect x="6" y="5" width="4" height="14" rx="1" />
              <rect x="14" y="5" width="4" height="14" rx="1" />
            </svg>
          ) : (
            <svg viewBox="0 0 24 24" className="size-3.5" fill="currentColor" aria-hidden>
              <path d="M8 5.5v13a1 1 0 0 0 1.5.86l10.4-6.5a1 1 0 0 0 0-1.72L9.5 4.64A1 1 0 0 0 8 5.5Z" />
            </svg>
          )}
        </button>
        <div className="mr-2 flex gap-1.5" role="tablist" aria-label="Choose slide">
          {frames.map((f, i) => (
            <button
              key={f.id}
              type="button"
              role="tab"
              aria-selected={i === index}
              aria-label={`Slide ${i + 1}: ${f.copy.title}`}
              onClick={() => goTo(i)}
              className={cx(
                "h-1.5 rounded-full transition-all",
                i === index ? "w-7 bg-cyan shadow-[0_0_10px_var(--color-cyan)]" : "w-2.5 bg-line-bright hover:bg-dim"
              )}
            />
          ))}
        </div>
        <button
          type="button"
          onClick={() => goTo(index - 1)}
          className="grid size-9 place-items-center rounded-full border border-line-bright bg-void/60 text-dim backdrop-blur transition hover:border-cyan hover:text-cyan"
          aria-label="Previous slide"
        >
          ‹
        </button>
        <button
          type="button"
          onClick={() => goTo(index + 1)}
          className="grid size-9 place-items-center rounded-full border border-line-bright bg-void/60 text-dim backdrop-blur transition hover:border-cyan hover:text-cyan"
          aria-label="Next slide"
        >
          ›
        </button>
      </div>

      {/* Autoplay progress. Freezes in place (amber) while paused instead of disappearing.
          Hidden under reduced motion, where the global stylesheet collapses every animation
          to near-zero duration anyway. */}
      {playing && !reducedMotion && (
        <div className="absolute inset-x-0 bottom-0 h-0.5 bg-line/40" aria-hidden data-testid="hero-progress">
          <div
            key={index}
            className={cx("h-full origin-left", paused ? "bg-amber/80" : "bg-cyan/80")}
            style={{
              animation: `hero-progress ${INTERVAL}ms linear forwards`,
              animationPlayState: paused ? "paused" : "running",
            }}
          />
        </div>
      )}
      <style>{`@keyframes hero-progress { from { transform: scaleX(0) } to { transform: scaleX(1) } }`}</style>
    </section>
  );
}
