import meta from "@/lib/generated/product-meta.json";
import type { Product } from "@/lib/types";

/**
 * Presentation data that the Flask API does not carry (images, component kind, socket,
 * wattage), keyed by product_id. Generated by scripts/sync-assets.mjs from data/catalog.json.
 * Products created later in the dashboard have no entry and fall back to their category art.
 */
export type Kind =
  | "cpu"
  | "motherboard"
  | "ram"
  | "ssd"
  | "hdd"
  | "gpu"
  | "psu"
  | "cooler"
  | "fan"
  | "paste"
  | "mouse"
  | "keyboard"
  | "monitor";

export type Socket = "LGA1851" | "AM5";

export interface ProductMeta {
  slug: string | null;
  kind: Kind | null;
  brand: string | null;
  socket: Socket | null;
  watt: number;
  image: string;
  blurDataURL: string | null;
  origin: "manufacturer" | "generated";
  accent: string;
}

type RawProduct = (typeof meta.products)[keyof typeof meta.products];
type RawCategory = (typeof meta.categories)[keyof typeof meta.categories];

const products = meta.products as Record<string, RawProduct>;
const categories = meta.categories as Record<string, RawCategory>;

export const CATEGORY_ACCENT: Record<number, string> = Object.fromEntries(
  Object.entries(categories).map(([id, c]) => [Number(id), c.accent])
);

export function metaFor(p: Pick<Product, "product_id" | "category_id">): ProductMeta {
  const m = products[String(p.product_id)];
  const cat = categories[String(p.category_id)];
  const accent = cat?.accent ?? "#22d3ee";
  if (m) {
    return {
      slug: m.slug,
      kind: m.kind as Kind,
      brand: m.brand,
      socket: (m.socket as Socket | null) ?? null,
      watt: m.watt,
      image: m.image,
      blurDataURL: m.blurDataURL,
      origin: m.origin as ProductMeta["origin"],
      accent,
    };
  }
  return {
    slug: null,
    kind: null,
    brand: null,
    socket: null,
    watt: 0,
    image: cat?.image ?? "/products/category-1.avif",
    blurDataURL: cat?.blurDataURL ?? null,
    origin: "generated",
    accent,
  };
}

export interface GalleryImage {
  src: string;
  blurDataURL: string | null;
}

/**
 * A product's pictures, primary first: its uploaded gallery if it has one, otherwise the
 * seeded photo (or the category art for products without one). The blur placeholder only
 * exists for the seeded photo.
 */
export function galleryFor(p: Pick<Product, "product_id" | "category_id" | "images">): GalleryImage[] {
  const m = metaFor(p);
  const srcs = p.images?.length ? p.images : [m.image];
  return srcs.map((src) => ({ src, blurDataURL: src === m.image ? m.blurDataURL : null }));
}

export const banners = meta.banners;
