/**
 * Writes the catalogue refresh for the Module 2 Flask database, generated from
 * data/catalog.json so the backend and this frontend can never drift apart.
 *
 *   docs/updated-seed.sql        PostgreSQL, one transaction, safe to run on the seeded DB
 *   docs/updated-seed-products.py  the same products as a Python list for seed_db.py
 *
 *   node scripts/export-seed.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_CONTENT } from "../lib/content.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const c = JSON.parse(readFileSync(join(ROOT, "data", "catalog.json"), "utf8"));
const q = (v) => (v === null || v === undefined ? "NULL" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v));
const catName = Object.fromEntries(c.categories.map((x) => [x.category_id, x.category_name]));

const sql = [];
sql.push(`-- RevoTech catalogue refresh (generated by scripts/export-seed.mjs from data/catalog.json)
-- Target: the Module 2 Flask/PostgreSQL database after seed_db.py has run.
--
-- What it does
--   1. Updates the 20 seeded products in place (same product_id, category_id) to their
--      current-generation replacements, with new specs, prices and stock, and inserts the
--      products added since (21+). Then moves the id sequence past the highest id.
--   2. Re-prices order_items to the new unit prices and recomputes each order's total_amount,
--      so historic orders stay internally consistent.
--   3. Sets the staff roles: one superadmin and one admin (the rest stay customers).
--   4. Creates site_content with the default homepage and About page content.
--
-- Roles: the frontend uses three - superadmin, admin, customer - in the existing users.role
-- column, so no migration is needed there. The routes behind them (GET /users and
-- PUT /users/<id>) do not exist in the Module 2 API yet; see the README.
--
-- It also adds six columns the frontend uses but the Flask Product model does not have yet:
--   official_url, overview, overview_source, specs_source (text), images (JSONB array of image
--   paths) and specs (JSONB array of {group?, label, value} rows).
-- Add the matching db.Column(...) fields and to_dict() keys to models.py before relying on them.
--
-- Categories are unchanged. Nothing is deleted. Wrapped in a transaction: all or nothing.

BEGIN;
`);

sql.push(`-- 0. frontend extensions to the products table (no-ops when they already exist)
ALTER TABLE products ADD COLUMN IF NOT EXISTS official_url VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS overview TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS overview_source VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS specs_source VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS specs JSONB NOT NULL DEFAULT '[]'::jsonb;
`);

// Upsert: the 20 products seed_db.py created are updated in place (same product_id), and
// products added since (21+) are inserted.
const COLS = ["product_id", "category_id", "product_name", "description", "price", "stock_quantity", "is_active", "official_url", "overview", "overview_source", "images", "specs_source", "specs"];
sql.push("-- 1. products (update the seeded ones, insert the new ones)");
for (const p of c.products) {
  const values = [
    p.product_id,
    p.category_id,
    q(p.product_name),
    q(p.description),
    p.price.toFixed(2),
    p.stock_quantity,
    p.is_active ? "TRUE" : "FALSE",
    q(p.official_url),
    q(p.overview),
    q(p.overview_source),
    `${q(JSON.stringify(p.images))}::jsonb`,
    q(p.specs_source),
    `${q(JSON.stringify(p.specs))}::jsonb`,
  ];
  sql.push(
    `INSERT INTO products (${COLS.join(", ")}, created_at) VALUES (${values.join(", ")}, CURRENT_TIMESTAMP)\n` +
      `  ON CONFLICT (product_id) DO UPDATE SET ${COLS.slice(1).map((k) => `${k} = EXCLUDED.${k}`).join(", ")}; -- ${catName[p.category_id]}`
  );
}
sql.push("SELECT setval(pg_get_serial_sequence('products', 'product_id'), (SELECT MAX(product_id) FROM products));\n");

sql.push(`
-- 2. keep existing orders consistent with the new prices
UPDATE order_items oi SET unit_price = p.price FROM products p WHERE oi.product_id = p.product_id;
UPDATE orders o SET total_amount = t.total
  FROM (SELECT order_id, SUM(quantity * unit_price) AS total FROM order_items GROUP BY order_id) t
  WHERE o.order_id = t.order_id;

-- 3. staff roles (passwords unchanged: password123)
${c.users
  .filter((u) => u.role !== "customer")
  .map((u) => `UPDATE users SET role = ${q(u.role)} WHERE email = ${q(u.email)};`)
  .join("\n")}

-- 4. editable site content (homepage and About page), one JSON document per page.
--    The frontend reads/writes it at /content/<key>; the Flask API needs a matching
--    GET/PUT route before NEXT_PUBLIC_API_BASE_URL can point there for this feature.
CREATE TABLE IF NOT EXISTS site_content (
  key VARCHAR(20) PRIMARY KEY,
  content JSONB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
${Object.entries(DEFAULT_CONTENT)
  .map(([key, doc]) => `INSERT INTO site_content (key, content) VALUES (${q(key)}, ${q(JSON.stringify(doc))}::jsonb) ON CONFLICT (key) DO NOTHING;`)
  .join("\n")}

COMMIT;

-- sanity check
SELECT product_id, product_name, price, stock_quantity, is_active FROM products ORDER BY product_id;`);

const py = [
  "# Drop-in replacement for the products seeded by seed_db.py (generated from data/catalog.json).",
  "# Each entry names its category by category_name so it can be looked up after categories are created.",
  "PRODUCTS = [",
  ...c.products.map(
    (p) =>
      `    {"category": ${JSON.stringify(catName[p.category_id])}, "product_name": ${JSON.stringify(p.product_name)}, ` +
      `"description": ${JSON.stringify(p.description)}, "price": ${p.price}, "stock_quantity": ${p.stock_quantity}, ` +
      `"is_active": ${p.is_active ? "True" : "False"}, "official_url": ${p.official_url ? JSON.stringify(p.official_url) : "None"}, ` +
      `"overview": ${p.overview ? JSON.stringify(p.overview) : "None"}, "overview_source": ${p.overview_source ? JSON.stringify(p.overview_source) : "None"}, ` +
      `"images": ${JSON.stringify(p.images)}, "specs_source": ${p.specs_source ? JSON.stringify(p.specs_source) : "None"}, ` +
      `"specs": ${JSON.stringify(p.specs)}},`
  ),
  "]",
  "",
];

mkdirSync(join(ROOT, "docs"), { recursive: true });
writeFileSync(join(ROOT, "docs", "updated-seed.sql"), sql.join("\n") + "\n");
writeFileSync(join(ROOT, "docs", "updated-seed-products.py"), py.join("\n"));
console.log(`  docs/updated-seed.sql (${c.products.length} products)\n  docs/updated-seed-products.py`);
